### ISSUE TITLE
MSVCP140.dll

### ISSUE THREAD

**Issue by iDarkEmpire** [zikdoz/L2DiscordPresence#1]
After connecting to the client, and the players start massive problems with msvcp140.dll
![chrome_WYlBZFayUZ](https://user-images.githubusercontent.com/36287788/214378445-95c0fe95-5bf7-42b2-8550-da0c663fb658.jpg)

**Comment by iDarkEmpire** [comment]
![chrome_b4a4njpALD](https://user-images.githubusercontent.com/36287788/214407945-e806ca7a-63d6-4070-853e-6f4db3b9edb3.jpg)
![chrome_W4UkIwNA7d](https://user-images.githubusercontent.com/36287788/214407978-d0aac012-6321-4447-bece-f45cbf93f66c.jpg)

**Comment by zikdoz** [comment]
@iDarkEmpire VCRUNTIME140 и MSVCP140 - это библиотеки из Microsoft Visual C++ Redistributable, который у твоих пользователей, видимо, не стоит. [Скачать можно тут](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) с сайта Microsoft. Скорее всего, нужна версия 2015-2022, на которую ссылку и дал.

В ридми проекта тоже укажу, что нужно будет эти дрова поставить

**Comment by iDarkEmpire** [comment]
да я нужные дллки закинул просто в клиент, и все работает нормально

**Comment by zikdoz** [comment]
> да я нужные дллки закинул просто в клиент

Не надо так делать :D
Лучше дрова нормально поставить. В других играх/софте пригодится
